# Generated by Django 3.0.4 on 2020-03-16 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('email', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('delay', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)], verbose_name='Задержка отправки')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('send_status', models.SmallIntegerField(choices=[(1, 'Неотправлено'), (2, 'Отправлено'), (3, 'Ошибка отправки')], default=1, verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Письма',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
